name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master
        with:
          ref: hexo
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.0
        with:
          version: ${{ matrix.node_version }}
      - name: build
        run: npm install && hexo g
      - name: Setup build
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          USERNAME: ${{secrets.DEPLOY_USER}}
          PASSWORD: ${{secrets.DEPLOY_PASSWORD}}
          HOST: ${{secrets.DEPLOY_HOST}}
          POTY: 22
          SOURCE: 'public'
          TARGET: '/www/wwwroot/vue.design.cn'
